version: '3.8'

services:
  test-app:
    image: ashoka007/otelv2-test-app:latest
    container_name: test-app
    build:
      context: ./test-app
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - OTEL_SERVICE_NAME=test-app
      - OTEL_TRACES_EXPORTER=console
      - OTEL_METRICS_EXPORTER=console
      - OTEL_LOGS_EXPORTER=console
      - OTEL_LOG_LEVEL=DEBUG
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOG_LEVEL=debug
      - OTEL_EXPORTER_OTLP_ENDPOINT=0.0.0.0:4317

  build-app:
    image: ashoka007/otelv2-build-app:latest
    container_name: build-app
    build:
      context: ./build-app
      dockerfile: Dockerfile
    ports:
      - 5001:5001
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - OTEL_SERVICE_NAME=build-app
      - OTEL_TRACES_EXPORTER=console
      - OTEL_METRICS_EXPORTER=console
      - OTEL_LOGS_EXPORTER=console
      - OTEL_LOG_LEVEL=DEBUG
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOG_LEVEL=debug
      - OTEL_EXPORTER_OTLP_ENDPOINT=0.0.0.0:4317

  workflow-app:
    image: ashoka007/otelv2-workflow-app:latest
    container_name: workflow-app
    build:
      context: ./workflow-app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    environment:
      - BUILD_URL=http://build-app:5001
      - TEST_URL=http://test-app:3001
      - OTEL_SERVICE_NAME=workflow-app
      - OTEL_TRACES_EXPORTER=console
      - OTEL_METRICS_EXPORTER=console
      - OTEL_LOGS_EXPORTER=console
      - OTEL_LOG_LEVEL=DEBUG
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOG_LEVEL=debug
      - OTEL_EXPORTER_OTLP_ENDPOINT=0.0.0.0:4317
